version: '3.7'

services:
  proxy:
    image: traefik:2.2
    restart: always
    container_name: traefik
    ports:
     - "80:80"     # HTTP
     - "443:443"   # HTTPS
     - "8080:8080" # Traefik Dashboard
    command: 
     - --api.insecure=true
     - --api.dashboard=true
     - --log.level=DEBUG
     # Provider Configuration
     - --providers.docker=true
     - --providers.docker.exposedbydefault=false
     - --providers.docker.network=web
     - --providers.file.filename=/dynamic.yml
     # Entrypoints Configuration
     - --entrypoints.web.address=:80
     - --entrypoints.web-secured.address=:443
     # SSL Configuration (Let's Encrypt)
     - --certificatesresolvers.mytlschallenge.acme.tlschallenge=true
     - --certificatesresolvers.mytlschallenge.acme.email=vardy@riseup.net
     - --certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - certs:/letsencrypt
     - ./dynamic.yml:/dynamic.yml
    networks:
     - web
    labels: # To expose dashboard
     - "traefik.enable=true"
     - "traefik.http.routers.api.service=api@internal"

volumes: 
  certs:

networks: 
  web:
    external: true